{% set name = "odc-stac" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 27bbfd29a683eaabcda775b038d38e6ddb4dfb0bd40a592cfbceaa2ef71c3cde

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - affine
    - datacube >=1.8.5 # need hashable GeoBox
    - jinja2
    - numpy
    - pandas
    - pystac >=1.0.0,<2
    - toolz
    - xarray

test:
  imports:
    - odc.stac
    - odc.index
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/opendatacube/odc-stac/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Tooling for converting STAC metadata to ODC data model
  description: |
    Load STAC `pystac.Items` into `xarray.Dataset`.

    ```python

       catalog = pystac.Client.open(...)
       query = catalog.search(...)
       xx = odc.stac.load(
           query.get_items(),
           bands=["red", "green", "blue"],
           output_crs="EPSG:32606",
           resolution=(100, -100),
       )
       xx.red.plot.imshow(col="time")
    ```

  doc_url: https://odc-stac.readthedocs.io/
  dev_url: https://github.com/opendatacube/odc-stac/

extra:
  recipe-maintainers:
    - kirill888
    - gadomski
    - alexgleith
